title: Glen Muthoka Mutinda - Portfolio
email: glenmuthokaq@gmail.com
description: >-
  Electrical & Electronics Engineering student specializing in embedded systems, 
  cybersecurity, and mixed-signal processing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username: Bananz0
linkedin_username: glenmuthoka

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor